# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97f65e7dd9325f50fbdb9a0117c605ad98a1286f8ffeb46bace2d7bb78d480986794b62baa89fdc2fab2ff1cd26fdf54feb034196eacb6ab3a1ad2628b080b22

test:
  secret_key_base: a4d0989b56d5fba511707bf71d63fb749b63efb73f3abf7542d460491e1b29b40745347d7bdccfedd6dcd7ac7c535778fa17c911dd0be14ae36b094796267537

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
